### ISSUE TITLE
Impossible values

### ISSUE THREAD

**Issue by jordanlandry** [Can1Cyp2/Minesweeper---Remake#8]
![image](https://user-images.githubusercontent.com/66219559/212987578-a4026aef-8bb9-47a9-ae04-c131fd4a8101.png)

The 2 in the middle is not possible as there is only one bomb nearby, yet it says 2,

![image](https://user-images.githubusercontent.com/66219559/212987753-e8540e21-a4d3-4d39-baca-465fed6a4d45.png)
Here is another example.

![image](https://user-images.githubusercontent.com/66219559/212988099-78a65bfc-7c59-4026-b7e7-65e5a091fb5d.png)
In this one, there is a 2 that should be a 3

![image](https://user-images.githubusercontent.com/66219559/212988276-f097816f-6635-4f39-ad52-f59c86d6bacf.png)

**Comment by jordanlandry** [comment]
![image](https://user-images.githubusercontent.com/66219559/212996156-546befad-2eb1-4f41-800b-8c49c40aedd2.png)

I found that the issue is when the bombs are created, it sometimes creates the same x and y position. (See Index 2 and Index 9)

![image](https://user-images.githubusercontent.com/66219559/212996502-eac29ed3-0851-423e-b916-60cf12f36f17.png)

The issue is the while loop as it will always be false since objects can't be compared using includes.

**Comment by Can1Cyp2** [comment]
Thank you for your thorough explanation. The issue has been resolved thanks to your edits. Great work!
